version: "2"
services:
    postgres:
        image: postgres:latest
        container_name: postgres_database
        volumes:
            - .var/postgres/data:/var/lib/postgresql/data
            - .var/postgres/conf:/etc/postgresql/postgresql.conf
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"